In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
from sklearn.impute import SimpleImputer

In [3]:
df=pd.read_csv("loan_approval_data.csv")

In [5]:
df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Applicant_ID        950 non-null    float64
 1   Applicant_Income    950 non-null    float64
 2   Coapplicant_Income  950 non-null    float64
 3   Employment_Status   950 non-null    object
 4   Age                 950 non-null    float64
 5   Marital_Status      950 non-null    object
 6   Dependents          950 non-null    float64
 7   Credit_Score        950 non-null    float64
 8   Existing_Loans      950 non-null    float64
 9   DTI_Ratio           950 non-null    float64
 10  Savings             950 non-null    float64
 11  Collateral_Value    950 non-null    float64
 12  Loan_Amount         950 non-null    float64
 13  Loan_Term           950 non-null    float64
 14  Loan_Purpose        950 non-null    object
 15  Property_Area       950 non-null    object
 16  Education_Level     950 non-null    object
 17  Gender              950 non-null    object
 18  Employer_Category   950 non-null    object
 19  Loan_Approved       950 non-null    object
dtypes: float64(12), object(8)
memory usage: 156.4+ KB

In [6]:
df.describe()

,Applicant_ID,Applicant_Income,Coapplicant_Income,Age,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term
count,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000,950.000000
mean,501.220000,10852.571579,5082.455789,39.971579,1.474737,676.033684,1.950526,0.347263,9940.452632,24802.792632,20522.825263,48.000000
std,289.608451,5061.632859,2943.161570,11.139797,1.105067,71.346015,1.406246,0.144341,5860.736885,14345.696031,11504.142575,24.245322
min,1.000000,2009.000000,1.000000,21.000000,0.000000,550.000000,0.000000,0.100000,65.000000,36.000000,1015.000000,12.000000
25%,250.250000,6730.750000,2472.750000,30.250000,1.000000,616.250000,1.000000,0.220000,4760.250000,12698.250000,9806.250000,24.000000
50%,499.500000,10548.000000,5205.500000,40.000000,1.000000,678.000000,2.000000,0.340000,9880.500000,24321.000000,21210.500000,48.000000
75%,752.750000,15190.000000,7620.750000,49.000000,2.000000,737.000000,3.000000,0.480000,15074.500000,36947.000000,30263.000000,72.000000
max,1000.000000,19988.000000,9996.000000,59.000000,3.000000,799.000000,4.000000,0.600000,19996.000000,49954.000000,39995.000000,84.000000

In [7]:
df.isnull().sum()

Applicant_ID          50
Applicant_Income      50
Coapplicant_Income    50
Employment_Status     50
Age                   50
Marital_Status        50
Dependents            50
Credit_Score          50
Existing_Loans        50
DTI_Ratio             50
Savings               50
Collateral_Value      50
Loan_Amount           50
Loan_Term             50
Loan_Purpose          50
Property_Area         50
Education_Level       50
Gender                50
Employer_Category     50
Loan_Approved         50
dtype: int64

In [9]:
num_i=SimpleImputer(strategy='mean')

In [10]:
numerical_columns=df.select_dtypes(include=["number"]).columns

In [11]:
numerical_columns

Index(['Applicant_ID', 'Applicant_Income', 'Coapplicant_Income', 'Age',
       'Dependents', 'Credit_Score', 'Existing_Loans', 'DTI_Ratio', 'Savings',
       'Collateral_Value', 'Loan_Amount', 'Loan_Term'],
      dtype='object')

In [13]:
df[numerical_columns]=num_i.fit_transform(df[numerical_columns])

In [15]:
categorical_columns=df.select_dtypes(include=["object"]).columns

In [19]:
obj_i=SimpleImputer(strategy='most_frequent')
df[categorical_columns]=obj_i.fit_transform(df[categorical_columns])

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Applicant_ID        1000 non-null   float64
 1   Applicant_Income    1000 non-null   float64
 2   Coapplicant_Income  1000 non-null   float64
 3   Employment_Status   1000 non-null   object
 4   Age                 1000 non-null   float64
 5   Marital_Status      1000 non-null   object
 6   Dependents          1000 non-null   float64
 7   Credit_Score        1000 non-null   float64
 8   Existing_Loans      1000 non-null   float64
 9   DTI_Ratio           1000 non-null   float64
 10  Savings             1000 non-null   float64
 11  Collateral_Value    1000 non-null   float64
 12  Loan_Amount         1000 non-null   float64
 13  Loan_Term           1000 non-null   float64
 14  Loan_Purpose        1000 non-null   object
 15  Property_Area       1000 non-null   object
 16  Education_Level     1000 non-null   object
 17  Gender              1000 non-null   object
 18  Employer_Category   1000 non-null   object
 19  Loan_Approved       1000 non-null   object
dtypes: float64(12), object(8)
memory usage: 156.4+ KB

In [21]:
#EDA

In [26]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
le=LabelEncoder()
df["Education_Level"]=le.fit_transform(df["Education_Level"])
df["Loan_Approved"]=le.fit_transform(df["Loan_Approved"])

In [27]:
cols=["Employment_Status","Marital_Status","Loan_Purpose","Property_Area","Gender","Employer_Category"]

In [34]:
ohe=OneHotEncoder(drop="first",sparse_output=False,handle_unknown="ignore")

In [36]:
e=ohe.fit_transform(df[cols])

In [37]:
enco=pd.DataFrame(e,columns=ohe.get_feature_names_out(cols),index=df.index)

In [38]:
df=pd.concat([df.drop(columns=cols),enco],axis=1)

In [39]:
df.head()

,Applicant_ID,Applicant_Income,Coapplicant_Income,Age,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,...,Loan_Purpose_Education,Loan_Purpose_Home,Loan_Purpose_Personal,Property_Area_Semiurban,Property_Area_Urban,Gender_Male,Employer_Category_Government,Employer_Category_MNC,Employer_Category_Private,Employer_Category_Unemployed
0,1.0,17795.0,1387.0,51.0,0.0,637.0,4.0,0.53,19403.0,45638.0,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
1,2.0,2860.0,2679.0,46.0,3.0,621.0,2.0,0.30,2580.0,49272.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0
2,3.0,7390.0,2106.0,25.0,2.0,674.0,4.0,0.20,13844.0,6908.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
3,4.0,13964.0,8173.0,40.0,2.0,579.0,3.0,0.31,9553.0,10844.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,5.0,13284.0,4223.0,31.0,2.0,721.0,1.0,0.29,9386.0,37629.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0

In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 29 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Applicant_ID                     1000 non-null   float64
 1   Applicant_Income                 1000 non-null   float64
 2   Coapplicant_Income               1000 non-null   float64
 3   Age                              1000 non-null   float64
 4   Dependents                       1000 non-null   float64
 5   Credit_Score                     1000 non-null   float64
 6   Existing_Loans                   1000 non-null   float64
 7   DTI_Ratio                        1000 non-null   float64
 8   Savings                          1000 non-null   float64
 9   Collateral_Value                 1000 non-null   float64
 10  Loan_Amount                      1000 non-null   float64
 11  Loan_Term                        1000 non-null   float64
 12  Education_Level                  1000 non-null   int64
 13  Loan_Approved                    1000 non-null   int64
 14  Employment_Status_Salaried       1000 non-null   float64
 15  Employment_Status_Self-employed  1000 non-null   float64
 16  Employment_Status_Unemployed     1000 non-null   float64
 17  Marital_Status_Single            1000 non-null   float64
 18  Loan_Purpose_Car                 1000 non-null   float64
 19  Loan_Purpose_Education           1000 non-null   float64
 20  Loan_Purpose_Home                1000 non-null   float64
 21  Loan_Purpose_Personal            1000 non-null   float64
 22  Property_Area_Semiurban          1000 non-null   float64
 23  Property_Area_Urban              1000 non-null   float64
 24  Gender_Male                      1000 non-null   float64
 25  Employer_Category_Government     1000 non-null   float64
 26  Employer_Category_MNC            1000 non-null   float64
 27  Employer_Category_Private        1000 non-null   float64
 28  Employer_Category_Unemployed     1000 non-null   float64
dtypes: float64(27), int64(2)
memory usage: 226.7 KB

In [46]:
x=df.drop(columns=["Loan_Approved"],axis=1)
y=df["Loan_Approved"]
from sklearn.preprocessing import StandardScaler
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
ss=StandardScaler()
x_scaled=ss.fit_transform(x_train)
x_test_scaled=ss.transform(x_test)

from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_scaled,y_train)
y_pred=lr.predict(x_test_scaled)
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
print("logistic regression")
print("precison :",precision_score(y_test,y_pred))
print("accuracy :",accuracy_score(y_test,y_pred))
print("recall :", recall_score(y_test,y_pred))
print("f1 score :", f1_score(y_test,y_pred))
print("confusion_matrix :", confusion_matrix(y_test,y_pred))

logistic regression
precison : 0.7868852459016393
accuracy : 0.87
recall : 0.7868852459016393
f1 score : 0.7868852459016393
confusion_matrix : [[126  13]
 [ 13  48]]

In [48]:
from sklearn.neighbors import KNeighborsClassifier
kn= KNeighborsClassifier()
kn.fit(x_scaled,y_train)
y_pred=kn.predict(x_test_scaled)
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
print("KNN classification")
print("precison :",precision_score(y_test,y_pred))
print("accuracy :",accuracy_score(y_test,y_pred))
print("recall :", recall_score(y_test,y_pred))
print("f1 score :", f1_score(y_test,y_pred))
print("confusion_matrix :", confusion_matrix(y_test,y_pred))

logistic regression
precison : 0.5957446808510638
accuracy : 0.74
recall : 0.45901639344262296
f1 score : 0.5185185185185185
confusion_matrix : [[120  19]
 [ 33  28]]

In [49]:
from sklearn.naive_bayes import GaussianNB
gn=  GaussianNB()
gn.fit(x_scaled,y_train)
y_pred=gn.predict(x_test_scaled)
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
print("naive bayes classification")
print("precison :",precision_score(y_test,y_pred))
print("accuracy :",accuracy_score(y_test,y_pred))
print("recall :", recall_score(y_test,y_pred))
print("f1 score :", f1_score(y_test,y_pred))
print("confusion_matrix :", confusion_matrix(y_test,y_pred))

naive bayes classification
precison : 0.8035714285714286
accuracy : 0.865
recall : 0.7377049180327869
f1 score : 0.7692307692307693
confusion_matrix : [[128  11]
 [ 16  45]]